#
# "R script""
# An evaluation in R.

# Put all outputs and metrics in the same folder
output_path = "/scratch/lchladek/experiments"
metrics_path = "/scratch/lchladek/experiments"
experiments_folder = "/scratch/lchladek/experiments"

[slurm]
experiment_name = "RBO experimental evaluation"
output_folder = "/scratch/lchladek/slurm-output"
partition = "compute-p2"
account = "education-eemcs-courses-cse3000"
mail_type = "ALL"
#modules = ["2024r1", "r/4.3.0", "r-purrr", "r-dplyr", "r-ggplot2", "r-glue" ]

[program.11-synthetic-data]
binary = "./11-synthetic-rankings.R"
afterscript = "./afterscript.sh"
arguments = [
	     "--workers", "8",
	     "--permutation-limit", "100000",
	     "--earth-movers-distance",
#       "--workers", "8"
       "--workers", "1"
	    ]

[input.p]
arguments = [
       "--length-range", "subparam|size.length_from", "subparam|size.length_to",
       "--item-count", "subparam|size.item_count",
	     "--seed", "param|seed",
       "--ranking-count", "10000",
	     "--rbo-p", "0.9"
	     ]

[input.p_variable]
arguments = [
       "--length-range", "subparam|size.length_from", "subparam|size.length_to",
       "--item-count", "subparam|size.item_count",
	     "--seed", "param|seed",
       "--ranking-count", "1000",
	     "--rbo-p", "0.75", "0.8", "0.85", "0.9", "0.95"
	     ]

[parameter.size.sub.length_from]
values = ["6", "12", "18", "24"]

[parameter.size.sub.length_to]
values = ["11", "17", "23", "29"]

[parameter.size.sub.item_count]
values = ["12", "18", "24", "30"]

[parameter.seed]
values = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

[resource_limits]
time_limit = "36000s"
cpus = 8
mem_per_cpu = 512